### ISSUE TITLE
Backwards compatibility broken in 2.5.0

### ISSUE THREAD

**Issue by zawias-pro** [TypeCtrl/tinycolor#122]
I used to import interfaces in my typescript app like this:
```ts
import { RGBA } from '@ctrl/tinycolor/interfaces';
```
but after upgrade to 2.5.0 I get an error:
```
TS2307: Cannot find module '@ctrl/tinycolor/interfaces'.
```
Imports must be changed manually:
```ts
import { RGBA } from '@ctrl/tinycolor/dist/interfaces';
```
***
I found this issue critical, because it can unexpectedly affect each TS app that have tinycolor as a dependency in following manner:
```
"@ctrl/tinycolor": "^2.2.1",
```
Like I used to have above entry in my `package.json`.

**Comment by zawias-pro** [comment]
@scttcper

**Comment by scttcper** [comment]
@zawias-pro okay that looks like it was a bug to begin with. All imports should be "@ctrl/tinycolor" fixed in latest soon
